# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'News' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for News
  platform :ios, '9.0'
  pod 'Firebase/Core'
  # pod 'Firebase/Storage', '~> 5.3.0'
  pod 'Firebase/Database'
  pod 'Firebase/Functions'
  pod 'Firebase/Firestore'
  target 'NewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'News-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for News-tvOS

  target 'News-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
